export const SET_USER = "SET_USER";
export const SET_LOADING_STATUS = "SET_LOADING_STATUS";
export const GET_ARTICLES = "GET_ARTICLES";
export const SET_DARK_MODE = "SET_DARK_MODE";

export const UPDATE_INTRODUCTION = "UPDATE_INTRODUCTION";
export const UPDATE_RESOURCES = "UPDATE_RESOURCES";
